config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :visitors
  resources :vouchers
  
 root "visitors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :name, :cpf, :visit_sector, :observation, presence: true
  validates :cpf, uniqueness: true

  # Defina as colunas que voce deseja habilitar para pesquisa
  def self.ransackable_attributes(auth_object = nil)
    %w[name cpf]
  end

  enum fields_visit_sector: {
    Gabinete: 'Gabinete',
    CTIGI: 'CTIGI',
    RH: 'RH',
    UGP_Prévio: 'UGP_Prévio',
    Comunicação: 'Comunicação'
  }
  #KAMINARI
  paginates_per 10

end

app/models/voucher.rb
class Voucher < ApplicationRecord
  validates :user_name, :token, presence: true

  #KAMINARI
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_visitor, only: %i[ show edit update destroy ]

  def index
    @q = Visitor.ransack(params[:q])
    @visitors = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new 
    @visitor = Visitor.new
  end  

  def create 
    @visitor = Visitor.new(visitor_params)

    if valid_cpf?(visitor_params[:cpf]) && @visitor.save
      redirect_to @visitor
    else
      @cpf_error = 'CPF inválido!'
      render :new
    end
  end

  def show; end

  def edit; end

  def update 
    @visitor.update(visitor_params)

    if valid_cpf?(visitor_params[:cpf]) && @visitor.save
      redirect_to @visitor
    else
      @cpf_error = 'CPF inválido!'
      render :edit
    end
  end

  def destroy
    @visitor.destroy

    redirect_to visitors_path
  end

  private 

  def valid_cpf?(cpf)
    CPF.valid?(cpf)
  end 

  def visitor_params
    params.require(:visitor).permit(:name, :cpf, :visit_sector, :observation)
  end

  def fetch_visitor
    @visitor = Visitor.find(params[:id]) 
  end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
        before_action :authenticate_user!
        before_action :set_voucher, only: [:show, :edit, :update, :destroy]
      
        def index
          @vouchers = Voucher.all.page(params[:page])   
        end
      
        def show
        end
      
        def new
          @voucher = Voucher.new
        end
      
        def create
          @voucher = Voucher.new(voucher_params)
          if @voucher.save
            redirect_to @voucher, notice: 'Voucher was successfully created.'
          else
            render :new
          end
        end
      
        def edit
        end
      
        def update
          if @voucher.update(voucher_params)
            redirect_to @voucher, notice: 'Voucher was successfully updated.'
          else
            render :edit
          end
        end
      
        def destroy
          @voucher.destroy
          redirect_to vouchers_url, notice: 'Voucher was successfully destroyed.'
        end
      
        private
      
        def set_voucher
          @voucher = Voucher.find(params[:id])
        end
      
        def voucher_params
          params.require(:voucher).permit(:user_name, :token, :status)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cpf_formatted(cpf)
    cpf = CPF.new(cpf)
    cpf.formatted 
  end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Access</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  </head>
  
  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Access Control</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
     

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
          Options
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <%= render "layouts/menus/menu_navbar" %>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>

      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Topbar Search -->
            <%= render "layouts/menus/search" %>

            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Dropdown Information -->
              <%= render "layouts/menus/dropdown_information" %>
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <%= render 'layouts/menus/footer' %>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Logout Modal-->
    <%= render "layouts/menus/logout_modal" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'rails-ujs' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Access</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  </head>
  
  <body class="back">
    <div class="container">
      <div class="card-body p-0">
        <div class="center">
          <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Please Sign In</h3>   
              </div>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Access</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  </head>
  
  <body id="page-top">

          <div class="container-fluid">
            <%= yield %>
          </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'rails-ujs' %>
  </body>
</html>

app/views/layouts/menus/_dropdown_information.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>

    <%= image_tag "img.jpeg", alt: "...", class: "img-profile rounded-circle" %>
  </a>
  
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
    aria-labelledby="userDropdown">

    <%= link_to destroy_user_session_path, class:"dropdown-item", method: :delete do %>
    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
      Logout
    <%end%>
  </div>
</li>

app/views/layouts/menus/_footer.html.erb
<div class="container my-auto">
  <div class="copyright text-center my-auto">
    <span>Copyright &copy; Vice Governadoria do Estado do Ceará</span>
  </div>
</div>

app/views/layouts/menus/_logout_modal.html.erb
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  
  <div class="modal-dialog" role="document">

    <div class="modal-content">
    
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        Select "Logout" below if you are ready to end your current session.
      </div>
      
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="login.html">Logout</a>
      </div>

    </div>

  </div>

</div>

app/views/layouts/menus/_menu_navbar.html.erb
<li class="nav-item">

  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
    aria-expanded="true" aria-controls="collapseTwo">
    <i class="fas fa-fw fa-cog"></i>
    <span>Visitors</span>
  </a>

  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
   
    <div class="bg-white py-2 collapse-inner rounded">
      <h6 class="collapse-header">Components:</h6>
      <%= link_to 'Visitors List', visitors_path, class:"collapse-item" %>
      <%= link_to 'New Visitor', new_visitor_path, class:"collapse-item" %>
    </div>

  </div>
</li>

<!-- Nav Item - Utilities Collapse Menu -->
<li class="nav-item">
 
  <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
    aria-expanded="true" aria-controls="collapseUtilities">
    <i class="fas fa-fw fa-wrench"></i>
    <span>Voucher</span>
  </a>

  <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
    
    <div class="bg-white py-2 collapse-inner rounded">
      <h6 class="collapse-header">Components:</h6>
      <%= link_to 'Voucher List', vouchers_path, class:"collapse-item" %>
      <%= link_to 'New Voucher', new_voucher_path, class:"collapse-item" %>
    </div>

  </div>
</li>

app/views/layouts/menus/_search.html.erb
<% if controller_name == 'visitors' && action_name == 'index' %> 
  <%= search_form_for @q, class:"d-flex", role:"search" do |f| %>
    <div class="input-group">
      <%= f.search_field :name_cont, class:"form-control bg-light border-0 small", placeholder:"Search for..." %>
      <div class="input-group-append">
        <%= f.button "", class: "btn btn-primary" do %>      
          <i class="fas fa-search fa-sm"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/visitors/_form.html.erb
<%= simple_form_for visitor do |f| %>
  
  <% if @cpf_error %>
    <div class="alert alert-danger">
      <%= @cpf_error %>
    </div>
  <% end %>
  
  <p>
    <%= f.input :name %>
  </p>

  <p>
    <%= f.input :cpf %>
  </p>

  <p>
    <%= f.input :visit_sector, as: :select, collection: Visitor.fields_visit_sectors.keys.map { |sector| [sector.humanize, sector] }, input_html: { class: 'form-control' } %>
  </p>
  
  <p>
    <%= f.input :observation %>
  </p>

  <p>
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to "Back", visitors_path, class: 'btn btn-primary' %>
  </p>

<% end %>

app/views/visitors/edit.html.erb
<h2> Edit Visitor </h2>

<%= render 'form', visitor: @visitor %>

app/views/visitors/index.html.erb
<h2> Visitors </h2>

<table class="table table-hover" >
  <thead>
    <tr>      
      <th><strong>Name</strong></th>
      <th><strong>CPF</strong></th>
      <th><strong>Visit Sector</strong></th>
      <th><strong>Entry Date</strong></th>
      <th colspan="3" ><strong>Actions</strong></th>
    </tr>
  </thead>
  
  <tbody>
    <% @visitors.each do |visitor| %>     
      <tr> 
        <td> <%= visitor.name %> </td>
        <td> <%= visitor.cpf %> </td>
        <td> <%= visitor.visit_sector %> </td>
        <td> <%= visitor.created_at%> </td>
        <td> 
          <%= link_to visitor_path(visitor) do %>
            <i class="fas fa-eye"></i>
          <%end%>
        </td>
        <td> 
          <%= link_to edit_visitor_path(visitor) do %> 
            <i class="fas fa-edit"></i>
          <%end%>
        </td>
        <td> 
          <%= link_to visitor_path(visitor), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash"></i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
<%= paginate @visitors%>
</div>

app/views/visitors/new.html.erb
<h2> New Visitor </h2>


<%= render 'form', visitor: @visitor %>

app/views/visitors/show.html.erb
<article class="blog-post">

<h2 class="display-5 link-body-emphasis mb-4"> <%= @visitor.name %></h2>
<p class="blog-post-meta">CPF: <%= cpf_formatted(@visitor.cpf) %></p>
<p class="blog-post-meta">Visit Sector: <%= @visitor.visit_sector %></p>
<p class="blog-post-meta">Created At: <%= (@visitor.created_at) %></p>

<p>Observation:  <%= @visitor.observation %> </p>

<%= link_to 'Back', visitors_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_visitor_path(@visitor), class: 'btn btn-success' %>

</article>

app/views/vouchers/_form.html.erb
<%= simple_form_for voucher do |f| %>

  <p>
      <%= f.input :user_name %>
  </p>

  <p>
      <%= f.input :token %>
  </p>
    <p>
      <%= f.input :status %>
  </p>
  <p>
      <%= f.button :submit, class: 'btn btn-success' %>
      <%= link_to "Back", vouchers_path, class: 'btn btn-primary' %>
  </p>

<% end %>

app/views/vouchers/edit.html.erb
<h1>Edit Voucher</h1>

<%= render 'form', voucher: @voucher %>

app/views/vouchers/index.html.erb
<h1>Vouchers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Token</th>
      <th>Status</th>
      <th colspan="3" ><strong>Actions</strong></th>
    </tr>
  </thead>
  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= voucher.user_name %></td>
        <td><%= voucher.token %></td>
        <td><%= voucher.status %></td>

        <td>
            <%= link_to voucher_path(voucher) do %>
            <i class="fas fa-eye"></i>
            <%end%>
        </td>
        <td>
        <%= link_to edit_voucher_path(voucher) do %>
        <i class="fas fa-edit"></i>
        <%end%>
        </td>

        <td><%= link_to voucher_path(voucher), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash"></i>
        <%end%>
        </td>
      
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
<%= paginate @vouchers%>
</div>

app/views/vouchers/new.html.erb
<h1>New Voucher</h1>


<%= render 'form', voucher: @voucher %>

app/views/vouchers/show.html.erb
<article class="blog-post">

<p class="blog-post-meta">User: <%= @voucher.user_name %></p>

<p class="blog-post-meta">Token: <%= @voucher.token %></p>

<p class="blog-post-meta">Status: <%= @voucher.status %></p>


<p class="blog-post-meta">Created At: <%= (@voucher.created_at) %></p>



<%= link_to 'Back', vouchers_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_voucher_path(@voucher), class: 'btn btn-success' %>

</article>